### ISSUE TITLE
Ability to use external monitors without using dedicated GPU

### ISSUE THREAD

**Issue by chunga2020** [system76/laptop-suggestions#139]
### Why/User Benefit/User Problem

Having extra screen space is very useful. Currently, the only way to use an external monitor is by switching to the dedicated GPU; neither the `intel` nor the `hybrid` options of `system76-power graphics` work. This is not ideal as it means the laptop can get loud sooner as the fans spin up. In Windows, for instance, despite limiting maximum CPU performance to 50% (Windows doesn't seem to like this hardware), I can use my external monitor just fine, and the laptop stays quiet.

**Comment by timnolte** [comment]
I'm a bit disappointed by this fact and now regret asking my employer to buy me the Oryx Pro. I will be daily connecting and disconnecting an external display, I want to use the integrated graphics driver when not connected to an external display to maintain decent battery life.

**Comment by leviport** [comment]
@timnolte you tried hybrid graphics mode yet?

**Comment by timnolte** [comment]
@leviport 
> @timnolte you tried hybrid graphics mode yet? 

From everything I've seen in reviews and posted the hybrid mode only works for the built-in display you are required to reboot into dedicated GPU mode in order to use an external connected display.

**Comment by leviport** [comment]
That is old information. Hybrid now works for external displays.

**Comment by timnolte** [comment]
@leviport really, interesting, was there a Core Boot update that fixed this in the last few of months? A couple of reviews from like the last few months seemed to still show that that this was a problem. I'm excited to hear that this has been resolved.

**Comment by leviport** [comment]
It was the Nvidia 455.xx driver update actually. It brought prime offloading to Linux so that the iGPU can do some rendering and pass it through the dGPU to display ports. It's not without its [growing pains](https://github.com/pop-os/nvidia-graphics-drivers/issues/61) but it was a huge improvement over having to switch to Nvidia graphics mode every time you want to use an external display.

**Comment by radupopa2010** [comment]
https://github.com/pop-os/nvidia-graphics-drivers/issues/61#issuecomment-1358664499

This is still happening
```
nvidia-driver-525/jammy,now 525.60.11-1pop0~1670285463~22.04~b24c135 amd64 [installed,automatic]

lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy


lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Alder Lake-P Integrated Graphics Controller (rev 0c)
01:00.0 VGA compatible controller: NVIDIA Corporation GA104 [Geforce RTX 3070 Ti Laptop GPU] (rev a1)
```

**Comment by aisivan36** [comment]
This issue has not been solved until now. But on the latest Gnome 44.1 with Fedora 38 and Ubuntu 23.04 firing it with Wayland is kinda solve the problem but still see some issues when connecting to External monitor it has to be rebooted before I can use it.

**Comment by leviport** [comment]
If you have a bug to report, this is not the repository to do so in. This repo is for suggestions on features for our upcoming in-house laptops. Since external displays work on integrated graphics now, and this issue seems to be confusing users, I'm going to close it.
