### ISSUE TITLE
enable firewall at first installation

### ISSUE THREAD

**Issue by G0rd0n** [system76/laptop-suggestions#146]
### Why/User Benefit/User Problem
For the strong security and privacy oriented company mission I found it odd that ufw was disabled by default after the Pop_OS installation. This question appears to invite a lengthy discussion in the ubuntu community forums. Maybe S76 could take a leading role in tackling this issue.
  (Though I am still a noob on everything distro related, and am not sure if this could be enabled by default.)

### Description of the feature
Enable the firewall (ufw) during installation or provide a lasting choice.

**Comment by brs17** [comment]
This is a feature request for Pop!_OS, not a suggestion on laptop hardware. Feel free to open up an issue in https://github.com/pop-os/pop/issues
