### ISSUE TITLE
Embedded NFC

### ISSUE THREAD

**Issue by ghost** [system76/laptop-suggestions#44]
It would be really cool to have an embedded NFC capability. I imagine you could pair a phone to a System76 app. There are things like KDE connect and GSConnect but I think you could do better.

**Comment by Dmole** [comment]
NFC is really bad for EM noise in electronics (google pixel failed in that regard).
and wired charging is more efficient, so you might as well plug it in.

wifi and ssh or send.firefox.com seem to fit most not plugged in requirements.

**Comment by ghost** [comment]
Umm... I didn't mention charging at all. Charging my phone via a laptop doesn't interest me. It's handy for temporary/quick communication between devices. I would not want or expect it to be always on. Seems like it isn't popular anyways.
