### ISSUE TITLE
self serviceable parts

### ISSUE THREAD

**Issue by 0lzi** [system76/laptop-suggestions#7]
### Why/User Benefit/User Problem
Easily upgradable parts or replaceable parts upon defect out of warranty ( battery , ram , harddrive/SSD , screens, keyboards, motherboards )
### Description of the feature
All the main components should be self serviceable and parts available to order upon request.

**Comment by AlNotSteve** [comment]
Self serviceable parts invariably come at the cost of bulk. Perhaps a middle ground of being able to replace SSD would be a better option.

**Comment by codeallstar** [comment]
I would trade a little bulk for replaceable RAM and SSD.

**Comment by TeamLinux01** [comment]
On bigger models, I wouldn't mind seeing a return of hot swap-able batteries.
