### ISSUE TITLE
Ship the whole mesa stack!

### ISSUE THREAD

**Issue by nottux** [system76/laptop-suggestions#71]
### Why/User Benefit/User Problem
By default Pop!_OS doesn't ship with whole mesa stack which *will* cause problems when user try to use 32bit drivers or gallium9. As an advanced user even i had black screen on a game because 32bit gallium9 wasn't installed. These drivers are not big and will make usage way smoother and easier (like nvidia counterpart)
### Description of the feature
Ship the whole mesa stack for amd/intel users. Create a dummy package for that.

**Comment by brs17** [comment]
This is a software request. Pop!_OS requests should be made here: https://github.com/pop-os/pop/issues or in the appropriate repository within the Pop!_OS organization.
