### ISSUE TITLE
Opencl 1.2 for AMD users

### ISSUE THREAD

**Issue by nottux** [system76/laptop-suggestions#72]
### Why/User Benefit/User Problem
Opencl 1.2 is the most widely used version and most programs target it as the lowest version. Opensource drivers are only supporting up to 1.1 and official amd installer is unnecessary and will trash the system.
### Description of the feature
[This bash script](https://gist.github.com/tuxutku/79daa2edca131c1525a136b650cdbe0a) Installs the proprietary opencl package directly via extracting files. It also creates the necessary files/directories in the working directory. Shipping a package with AMD eula and these files will be very useful. Its a very wanted feature and i have seen people using arch because of that. This only conflicts with `mesa-opencl-icd`

**Comment by brs17** [comment]
This is a software request. Pop!_OS requests should be made here: https://github.com/pop-os/pop/issues or in the appropriate repository within the Pop!_OS organization.
